# Generated by Django 3.2.25 on 2025-11-20 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='license_plate',
        ),
    ]
